import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Volumes and Bind Mounts - Docker Documentation",
  description: "Master data persistence in Docker - understand volumes for production, bind mounts for development, and Docker Compose."
};

export default function VolumesAndBindMountsPage() {
  return (
    <div className="content-area">
      <div className="container-fluid py-5 px-md-5">

        {/* PAGE HEADER */}
        <div className="page-intro-header mb-5 text-center text-md-start">
          <h1 className="doc-section-title mb-2" style={{ fontSize: '42px' }}>Volumes and Bind Mounts</h1>
          <p className="text-secondary opacity-75 fs-5 mb-0">
            Master data persistence in Docker - understand volumes for production, bind mounts for development, and Docker Compose.
          </p>
        </div>

        <div className="doc-content-grid">

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-hdd-fill"}></i>
              </div>
              <h2 className="doc-card-heading">Docker Volume</h2>
            </div>
            <div className="doc-card-body">
              
              <div dangerouslySetInnerHTML={{ __html: `<p>In the world of Docker, a volume is the preferred mechanism for persisting data generated by and used by Docker containers.</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<p>By default, any files created inside a container are stored on a writable container layer. This presents two problems: the data doesn't persist if the container is deleted, and it is difficult to get that data out of the container for another process to use. Volumes solve this by decoupling the storage from the container's lifecycle.</p>` }} />

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-exclamation-triangle-fill"}></i>
              </div>
              <h2 className="doc-card-heading">The Problem: The "Amnesia" Effect</h2>
            </div>
            <div className="doc-card-body">
              
              <div dangerouslySetInnerHTML={{ __html: `<p>Imagine you are building a FastAPI project. You write code that allows users to upload profile pictures.</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<div class="doc-alert doc-alert-warning" style="margin-top:1rem; margin-bottom:1rem;">
  <i class="bi bi-info-circle-fill"></i>
  <div><strong>The Goldfish Memory Effect:</strong> Just like a goldfish is said to have a 3-second memory, a container forgets everything that happened inside it the moment it is deleted or restarted. It starts completely fresh every time.</div>
</div>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<div class="doc-sub-cards-grid">
  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-1-circle-fill"></i></div>
      <h3 class="doc-sub-card-title">The Scenario</h3>
    </div>
    <div class="doc-sub-card-body">
      <p>You run your FastAPI app in a Docker container. A user uploads <code>my-photo.jpg</code>. Docker saves it inside the container's internal folder (e.g., <code>/app/uploads</code>).</p>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-2-circle-fill"></i></div>
      <h3 class="doc-sub-card-title">The Crash</h3>
    </div>
    <div class="doc-sub-card-body">
      <p>Your app crashes or you need to update your code, so you stop and delete the container to start a fresh one.</p>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-3-circle-fill"></i></div>
      <h3 class="doc-sub-card-title">The Loss</h3>
    </div>
    <div class="doc-sub-card-body">
      <p>Because the container was deleted, the internal <code>/app/uploads</code> folder is gone forever. Your user's photo is deleted.</p>
    </div>
  </div>
</div>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<div class="doc-alert doc-alert-warning" style="margin-top:1rem"><i class="bi bi-exclamation-circle-fill"></i><div><strong>The Problem Statement:</strong> Containers are "ephemeral" (temporary). Anything written inside them disappears when the container is removed.</div></div>` }} />

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-safe-fill"}></i>
              </div>
              <h2 className="doc-card-heading">The Solution: Volumes (The "External Hard Drive")</h2>
            </div>
            <div className="doc-card-body">
              
              <div dangerouslySetInnerHTML={{ __html: `<p>A volume acts like an external hard drive for your container. You tell Docker: <em>"Hey, even though this folder looks like it's inside the container, actually save everything to this specific spot on my physical computer."</em></p>` }} />

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-lightbulb-fill"}></i>
              </div>
              <h2 className="doc-card-heading">Noob-Friendly Example: The FastAPI Uploads</h2>
            </div>
            <div className="doc-card-body">
              <div dangerouslySetInnerHTML={{ __html: `<p>Instead of saving directly to the container's temporary memory, you "mount" a volume:</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<ul style="color:var(--text-secondary);line-height:2;padding-left:1.5rem">
  <li><strong>Step 1:</strong> You create a volume named <code>user_data</code>.</li>
  <li><strong>Step 2:</strong> You tell Docker: "Link <code>user_data</code> to the container's <code>/app/uploads</code> folder."</li>
  <li><strong>Step 3:</strong> Now, when a user uploads a photo, it bypasses the container's temporary storage and goes straight into <code>user_data</code>.</li>
  <li><strong>Step 4:</strong> You can delete, update, or crash the container 100 times. When the new container starts and links to <code>user_data</code>, the photos are still there waiting for it.</li>
</ul>` }} />

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-terminal-fill"}></i>
              </div>
              <h2 className="doc-card-heading">Practical CLI Example</h2>
            </div>
            <div className="doc-card-body">
              <div dangerouslySetInnerHTML={{ __html: `<p>When running your FastAPI image:</p>` }} />

              <pre className="doc-code-block mt-3 mb-3">
                <code className="language-bash">{`docker run -p 8000:8000 -v user_data:/app/uploads my-fastapi-app`}</code>
              </pre>

              <div dangerouslySetInnerHTML={{ __html: `<ul style="color:var(--text-secondary);line-height:2;padding-left:1.5rem">
  <li><code>-v</code>: This flag creates the volume connection.</li>
  <li><code>user_data</code>: The name of your persistent storage.</li>
  <li><code>/app/uploads</code>: The path inside your FastAPI project where the app expects to find files.</li>
</ul>` }} />

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-question-circle-fill"}></i>
              </div>
              <h2 className="doc-card-heading">Concept-Clearing Q&A</h2>
            </div>
            <div className="doc-card-body">
              <div dangerouslySetInnerHTML={{ __html: `<p>Common questions when starting out with Volumes.</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<div class="doc-sub-cards-grid d-flex flex-column gap-3">

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-database-fill"></i></div>
      <h3 class="doc-sub-card-title">1. Where to keep Database data?</h3>
    </div>
    <div class="doc-sub-card-body">
      <p>In the Docker world, every official database image (PostgreSQL, MySQL, MongoDB, etc.) is designed to store its data in a specific internal folder. You just "plug" a volume into that folder.</p>
      <p>For example, if you use PostgreSQL, the internal path where it stores everything is <code>/var/lib/postgresql/data</code>. Your command would look like this:</p>
      <pre style="background:#111827;padding:1rem;border-radius:0.5rem;border:1px solid #374151;color:#a5b4fc;margin-top:0.5rem"><code>docker run -v my_db_data:/var/lib/postgresql/data postgres</code></pre>
      <p style="margin-top: 0.5rem">Now, even if you delete the Postgres container and start a new one, all your tables and rows are perfectly safe inside <code>my_db_data</code>.</p>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-folder-fill"></i></div>
      <h3 class="doc-sub-card-title">2. Do I need 100 volumes for 100 folders?</h3>
    </div>
    <div class="doc-sub-card-body">
      <p>Technically, yes, if those folders are unrelated. However, in practice:</p>
      <ul style="color:var(--text-secondary);line-height:2;padding-left:1.5rem">
        <li><strong>One Volume, Multiple Sub-folders:</strong> You can mount one volume to a "parent" folder. If your app has <code>/app/data/uploads</code> and <code>/app/data/logs</code>, just mount a volume to <code>/app/data</code>.</li>
        <li><strong>Docker Compose:</strong> As a developer, you use a <code>docker-compose.yml</code> file to keep everything organized, so you don't even have to remember the volume mapping commands.</li>
      </ul>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-diagram-3-fill"></i></div>
      <h3 class="doc-sub-card-title">3. Can multiple containers share the same volume?</h3>
    </div>
    <div class="doc-sub-card-body">
      <p><strong>Yes!</strong> This is actually one of the superpowers of Docker volumes.</p>
      <p>For instance, you might have a web server container generating log files into a <code>logs_volume</code>, and a second "log processing" container reading from that exact same <code>logs_volume</code> simultaneously.</p>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-box-seam-fill"></i></div>
      <h3 class="doc-sub-card-title">4. What happens if I mount an empty volume to a folder with files?</h3>
    </div>
    <div class="doc-sub-card-body">
      <p>Docker is smart. If you mount a completely new, empty volume into a container directory that already contains files (baked into the image), Docker will <strong>copy the existing files</strong> into the volume first, and then mount it.</p>
      <p>This means you don't lose the default configurations or files that came with the image!</p>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-robot"></i></div>
      <h3 class="doc-sub-card-title">5. Cross-Compiling (e.g., Tesseract on Windows for Linux)?</h3>
    </div>
    <div class="doc-sub-card-body">
      <p style="margin-bottom:0.5rem"><strong>Question:</strong> "Let's say I am creating a binary of Tesseract using Docker on my Windows machine, but I need it for a Linux zipped deployment (like AWS Lambda). Do I use a Bind Mount for that because I want to copy the zip from my OS back to the cloud?"</p>
      <p><strong>Answer: Yes, absolutely!</strong> This is a perfect use case for a Bind Mount.</p>
      <ul style="color:var(--text-secondary);line-height:1.8;padding-left:1.5rem">
        <li>You spin up a Linux container and "bind mount" a folder from your Windows machine into it.</li>
        <li>The container compiles the Tesseract binary built perfectly for Linux environments.</li>
        <li>The container then places the final <code>.zip</code> file directly into that bind-mounted folder.</li>
        <li>Once the container exits, the Linux-compiled zip is sitting right there on your Windows desktop, ready for you to upload!</li>
      </ul>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-shield-exclamation"></i></div>
      <h3 class="doc-sub-card-title">6. Can a Volume or Bind Mount infect my Host OS with a virus?</h3>
    </div>
    <div class="doc-sub-card-body">
      <p style="margin-bottom:0.5rem"><strong>Question:</strong> "If a container gets a virus, can it spread to my actual laptop (Host OS) through a Volume or Bind Mount?"</p>
      <p><strong>Answer: Yes, but with conditions!</strong> Volumes and Bind Mounts are direct file-sharing mechanisms.</p>
      <ul style="color:var(--text-secondary);line-height:1.8;padding-left:1.5rem">
        <li>If a malicious container writes a ransomware file or script into a <strong>Bind Mount</strong> folder, that file immediately exists on your Host OS (e.g., your Desktop).</li>
        <li>However, the virus <strong>cannot automatically execute itself</strong> on your Host OS unless you (or another program on your laptop) double-clicks or runs that infected file.</li>
        <li><strong>Security Rule:</strong> Only mount folders that contain files the container absolutely needs to read or write. Never mount your entire <code>C:\\</code> drive or root <code>/</code> directory into a container!</li>
      </ul>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-usb-symbol"></i></div>
      <h3 class="doc-sub-card-title">7. Are Volumes/Bind Mounts the <em>only</em> way Docker shares with the OS?</h3>
    </div>
    <div class="doc-sub-card-body">
      <p style="margin-bottom:0.5rem"><strong>Question:</strong> "Are these the only possible sharable sections between the OS and Docker?"</p>
      <p><strong>Answer: No!</strong> Volumes and Bind Mounts are for sharing <strong>Files/Storage</strong>. But there are two other massive shared spaces:</p>
      <ul style="color:var(--text-secondary);line-height:1.8;padding-left:1.5rem">
        <li><strong>The Network (Ports):</strong> When you use <code>-p 8000:8000</code>, you are sharing a "doorway" (a network port). Traffic from your Host OS port 8000 goes straight into the container's port 8000.</li>
        <li><strong>System Devices (Advanced):</strong> You can share physical hardware using the <code>--device</code> flag. For example, you can give a container direct access to your USB WebCam (<code>/dev/video0</code>) or your Graphics Card (GPU) for AI training!</li>
      </ul>
    </div>
  </div>

</div>` }} />

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-table"}></i>
              </div>
              <h2 className="doc-card-heading">Summary Table</h2>
            </div>
            <div className="doc-card-body">
              
              <div dangerouslySetInnerHTML={{ __html: `<div class="doc-table-wrapper shadow-sm">
  <table class="table table-dark table-hover doc-table mb-0">
    <thead>
      <tr>
        <th>Data Type</th>
        <th>Needs a Volume?</th>
        <th>Why?</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>Source Code</strong></td>
        <td>No</td>
        <td>It's built into the Image.</td>
      </tr>
      <tr>
        <td><strong>Database Rows</strong></td>
        <td>Yes</td>
        <td>You can't lose your users' accounts!</td>
      </tr>
      <tr>
        <td><strong>User Uploads</strong></td>
        <td>Yes</td>
        <td>You can't ask users to re-upload photos.</td>
      </tr>
      <tr>
        <td><strong>App Logs</strong></td>
        <td>Optional</td>
        <td>Only if you need to analyze them after a crash.</td>
      </tr>
    </tbody>
  </table>
</div>` }} />

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-stack"}></i>
              </div>
              <h2 className="doc-card-heading">The "All-in-One" Solution: Docker Compose</h2>
            </div>
            <div className="doc-card-body">
              
              <div dangerouslySetInnerHTML={{ __html: `<p>Since you're moving from pure coding toward DevOps, seeing how a database and an app live together is the next logical step. Instead of running two separate, massive commands, we use Docker Compose.</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<p>Think of Docker Compose as a blueprint for your entire project. Instead of remembering which volume goes to which container, you write it down once in a file named <code>docker-compose.yml</code>.</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<p>Here is how you would set up your FastAPI app and a Postgres Database together:</p>` }} />

              <pre className="doc-code-block mt-3 mb-3">
                <code className="language-yaml">{`version: '3.8'

services:
  # Service 1: The Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mypassword

  # Service 2: Your FastAPI App
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - user_uploads:/app/uploads
    depends_on:
      - db

volumes:
  postgres_data:  # This stays safe even if the DB container is deleted
  user_uploads:   # This stays safe even if the FastAPI container is deleted`}</code>
              </pre>

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-lightning-charge-fill"}></i>
              </div>
              <h2 className="doc-card-heading">Wait, What About Bind Mounts?</h2>
            </div>
            <div className="doc-card-body">
              
              <div dangerouslySetInnerHTML={{ __html: `<p>Volumes are great for databases and permanent storage. But what if you are actively coding and want to see your changes instantly? Enter <strong>Bind Mounts</strong>.</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<p>A Bind Mount is like opening a direct "window" from the container into a specific folder on your actual laptop (like <code>/Users/you/project</code>).</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<div class="doc-alert doc-alert-info" style="margin-top:1rem; margin-bottom:1.5rem">
  <i class="bi bi-lightbulb-fill"></i>
  <div><strong>Developer Superpower:</strong> If you change a line of code on your laptop, the container sees it instantly through the window. This gives you Live Reloading!</div>
</div>` }} />

            </div>
          </div>

          {/* SECTION */}
          <div className="doc-section-card shadow-lg">
            <div className="doc-card-header-wrapper">
              <div className="heading-icon">
                <i className={"bi " + "bi-diagram-2"}></i>
              </div>
              <h2 className="doc-card-heading">Volume vs. Bind Mount (The Short Version)</h2>
            </div>
            <div className="doc-card-body">
              <div dangerouslySetInnerHTML={{ __html: `<p>If you're ever confused about which one to pick, use this simple cheat sheet:</p>` }} />

              <div dangerouslySetInnerHTML={{ __html: `<div class="doc-sub-cards-grid">
  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-safe-fill"></i></div>
      <h3 class="doc-sub-card-title">Docker Volume</h3>
    </div>
    <div class="doc-sub-card-body">
      <ul style="color:var(--text-secondary);line-height:2;padding-left:1.5rem">
        <li><strong>Who manages it?</strong> Docker.</li>
        <li><strong>Where is it?</strong> Hidden deep in Docker's internal engine files.</li>
        <li><strong>When to use:</strong> Databases (Postgres), user uploads, and production environments.</li>
      </ul>
    </div>
  </div>

  <div class="doc-sub-card">
    <div class="doc-sub-card-header">
      <div class="doc-sub-card-icon"><i class="bi bi-window"></i></div>
      <h3 class="doc-sub-card-title">Bind Mount</h3>
    </div>
    <div class="doc-sub-card-body">
      <ul style="color:var(--text-secondary);line-height:2;padding-left:1.5rem">
        <li><strong>Who manages it?</strong> You (The OS).</li>
        <li><strong>Where is it?</strong> A literal folder on your Desktop or Documents.</li>
        <li><strong>When to use:</strong> Local development (Live code reloading).</li>
      </ul>
    </div>
  </div>
</div>` }} />

            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
